//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Entities._837_Professional
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    
    public class Dependent_Professional_837
    {
        public Dependent_Professional_837()
        {
            this.CRC_ConditionsIndicator_Professional_837 = new HashSet<CRC_ConditionsIndicator_Professional_837>();
            this.REF_ReferenceIdentification_Professional_837 = new HashSet<REF_ReferenceIdentification_Professional_837>();
            this.DTP_DateTimePeriod_Professional_837 = new HashSet<DTP_DateTimePeriod_Professional_837>();
            this.PWK_PaperWork_Professional_837 = new HashSet<PWK_PaperWork_Professional_837>();
            this.K3_FileInfo_Professional_837 = new HashSet<K3_FileInfo_Professional_837>();
            this.HI_HealthCareInfoCode_Professional_837 = new HashSet<HI_HealthCareInfoCode_Professional_837>();
        }
        [Key]
        public int Dependentkey { get; set; }
        public Nullable<int> Subscriberkey { get; set; }
        public string PAT01_IndividualRelationshipCode { get; set; }
        public string PAT06_PatientDeathDate { get; set; }
        public string PAT08_PatientWeightPounds { get; set; }
        public string PAT09_Pregnant { get; set; }
        public string NM102_PatientTypeQualifier { get; set; }
        public string NM103_PatientLastOrOrganizationName { get; set; }
        public string NM104_PatientFirst { get; set; }
        public string NM105_PatientMiddle { get; set; }
        public string NM107_PatientSuffix { get; set; }
        public string N301_PatientAddr1 { get; set; }
        public string N302_PatientAddr2 { get; set; }
        public string N401_PatientCity { get; set; }
        public string N402_PatientState { get; set; }
        public string N403_PatientZip { get; set; }
        public string N404_PatientCountry { get; set; }
        public string N407_PatientCountrySubdivision { get; set; }
        public string DMG02_PatientBirthDate { get; set; }
        public string DMG03_PatientGenderCode { get; set; }
        public string REF02_PropertyCasualtyClaimNo { get; set; }
        public string REF02_PatientSocialSecurityNo { get; set; }
        public string REF02_MemberIdNo { get; set; }
        public string PER02_PatientContactName { get; set; }
        public string PER04_PatientPhoneNo { get; set; }
        public string PER06_PatientPhoneExtNo { get; set; }
        public int  Subscriber_Professional_837ID { get; set; }

        [ForeignKey("Subscriber_Professional_837ID")]
        public  Subscriber_Professional_837 Subscriber_Professional_837 { get; set; }
    
        public virtual ICollection<CRC_ConditionsIndicator_Professional_837> CRC_ConditionsIndicator_Professional_837 { get; set; }
        public virtual ICollection<REF_ReferenceIdentification_Professional_837> REF_ReferenceIdentification_Professional_837 { get; set; }
        public virtual ICollection<DTP_DateTimePeriod_Professional_837> DTP_DateTimePeriod_Professional_837 { get; set; }
        public virtual ICollection<PWK_PaperWork_Professional_837> PWK_PaperWork_Professional_837 { get; set; }
        public virtual ICollection<K3_FileInfo_Professional_837> K3_FileInfo_Professional_837 { get; set; }
        public virtual ICollection<HI_HealthCareInfoCode_Professional_837> HI_HealthCareInfoCode_Professional_837 { get; set; }
    }
}
