//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Entities._837_Professional
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public class MEA_Measurements_Professional_837
    {
        [Key]
        public int MEAkey { get; set; }
        public Nullable<int> ServiceLinekey { get; set; }
        public string MEA01_TestResultReferenceIdCode { get; set; }
        public string MEA02_TestResultQualifier { get; set; }
        public string MEA03_TestResultValue { get; set; }
    
        public virtual ServiceLine_Professional_837 ServiceLine_Professional_837 { get; set; }
    }
}
