//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Entities._837_Professional
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public class PER_AdministrativeCommunicationContact_Professional_837
    {
        [Key]
        public int PERkey { get; set; }
        public Nullable<int> Headerkey { get; set; }
        public Nullable<int> Infosourcekey { get; set; }
        public string PER02_ContactName { get; set; }
        public string PER0X_PhoneNo { get; set; }
        public string PER0X_PhoneExtNo { get; set; }
        public string PER0X_FaxNo { get; set; }
        public string PER0X_Email { get; set; }
    
        //public virtual Header_Professional_837 Header_Professional_837 { get; set; }
        public virtual InfoSource_Professional_837 InfoSource_Professional_837 { get; set; }
    }
}
