//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Entities._837_Professional
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public class PWK_PaperWork_Professional_837
    {
        [Key]
        public int PWKkey { get; set; }
        public Nullable<int> Claimskey { get; set; }
        public Nullable<int> ServiceLinekey { get; set; }
        public Nullable<int> Subscriberkey { get; set; }
        public Nullable<int> Dependentkey { get; set; }
        public string PWK01_AttachmentReportTypeCode { get; set; }
        public string PWK02_AttachmentTransmissionCode { get; set; }
        public string PWK05_AttachmentControlQualifier { get; set; }
        public string PWK06_AttachmentControlNo { get; set; }
    
        public virtual Claims_Professional_837 Claims_Professional_837 { get; set; }
        public virtual Dependent_Professional_837 Dependent_Professional_837 { get; set; }
        public virtual ServiceLine_Professional_837 ServiceLine_Professional_837 { get; set; }
        public virtual Subscriber_Professional_837 Subscriber_Professional_837 { get; set; }
    }
}
