//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Entities._837_Professional
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public class REF_ReferenceIdentification_Professional_837
    {
        [Key]
        public int REFkey { get; set; }
        public Nullable<int> Infosourcekey { get; set; }
        public Nullable<int> ServiceLinekey { get; set; }
        public Nullable<int> Claimskey { get; set; }
        public Nullable<int> Subscriberkey { get; set; }
        public Nullable<int> Dependentkey { get; set; }
        public Nullable<int> OtherSubscriberInfokey { get; set; }
        public string REF_LoopId { get; set; }
        public string REF01_ReferenceIdentificationQualifier { get; set; }
        public string REF02_ReferenceIdentifier { get; set; }
        public string REF04_1_ReferenceIdentificationQualifier { get; set; }
        public string REF04_2_ReferenceIdentifier { get; set; }
    
        public virtual Claims_Professional_837 Claims_Professional_837 { get; set; }
        public virtual Dependent_Professional_837 Dependent_Professional_837 { get; set; }
        public virtual InfoSource_Professional_837 InfoSource_Professional_837 { get; set; }
        public virtual OtherSubscriberInfo_Professional_837 OtherSubscriberInfo_Professional_837 { get; set; }
        public virtual Subscriber_Professional_837 Subscriber_Professional_837 { get; set; }
        public virtual ServiceLine_Professional_837 ServiceLine_Professional_837 { get; set; }
    }
}
