//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Entities._837_Professional
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public class ServiceDocument_Professional_837
    {
        public ServiceDocument_Professional_837()
        {
            this.FRM_SupportingDocument_Professional_837 = new HashSet<FRM_SupportingDocument_Professional_837>();
        }
        [Key]
        public int ServiceDocumentkey { get; set; }
        public Nullable<int> ServiceLinekey { get; set; }
        public string LQ01_CodeListQualifierCode { get; set; }
        public string LQ02_FormIdentifier { get; set; }
    
        public virtual ICollection<FRM_SupportingDocument_Professional_837> FRM_SupportingDocument_Professional_837 { get; set; }
        public virtual ServiceLine_Professional_837 ServiceLine_Professional_837 { get; set; }
    }
}
