//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI.Entities._837_Professional
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public class ServiceLineAdj_Professional_837
    {
        public ServiceLineAdj_Professional_837()
        {
            this.CAS_ClaimsAdjustment_Professional_837 = new HashSet<CAS_ClaimsAdjustment_Professional_837>();
        }
        [Key]
        public int ServiceLineAdjkey { get; set; }
        public Nullable<int> ServiceLinekey { get; set; }
        public string SVD01_OtherPayerPrimaryIdfr { get; set; }
        public string SVD02_ServiceLinePaidAmount { get; set; }
        public string SVD03_01_ProductServiceIdQlfr { get; set; }
        public string SVD03_02_ProcedureCode { get; set; }
        public string SVD03_03_ProcedureModifier1 { get; set; }
        public string SVD03_04_ProcedurModifier2 { get; set; }
        public string SVD03_05_ProcedureModifier3 { get; set; }
        public string SVD03_06_ProcedureModifier4 { get; set; }
        public string SVD03_07_ProcedureCodeDesc { get; set; }
        public string SVD05_PaidServiceUnitCount { get; set; }
        public string SVD06_LineNumber { get; set; }
        public string DTP03_AdjudicationPaymentDate { get; set; }
        public string AMT02_RemainingPatientLiability { get; set; }
    
        public virtual ICollection<CAS_ClaimsAdjustment_Professional_837> CAS_ClaimsAdjustment_Professional_837 { get; set; }
        public virtual ServiceLine_Professional_837 ServiceLine_Professional_837 { get; set; }
    }
}
