//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI_Entites._999Entites
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Context_999
    {
        [Key]
        public int ContextKey { get; set; }
        public Nullable<int> ImplementationDataElementkey { get; set; }
        public Nullable<int> ImplementationDataSegmentkey { get; set; }
        public string CTX01_ContextIdentification { get; set; }
        public string CTX01_01_ContextName { get; set; }
        public string CTX01_02_ContextReference { get; set; }
        public string CTX02_SegmentIdCode { get; set; }
        public string CTX03_SegmentPositionInTransactionCode { get; set; }
        public string CTX04_LoopIdentifierCode { get; set; }
        public string CTX05_PositionInSegment { get; set; }
        public string CTX05_01_ElementPositionInSegment { get; set; }
        public string CTX05_02_ComponentDataElementPositionInSegment { get; set; }
        public string CTX05_03_RepeatingDataElementPosition { get; set; }
        public string CTX06_ReferenceInSegment { get; set; }
        public string CTX06_01_DataElementReferenceNumber { get; set; }
        public string CTX06_02_DataElementReferenceNumber { get; set; }

        public virtual ImplementationDataSegment_999 ImplementationDataSegment_999 { get; set; }
        public virtual ImplementationDataElement_999 ImplementationDataElement_999 { get; set; }
    }
}
