//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI_Entites._999Entites
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class FunctionalGroup_999
    {
        public FunctionalGroup_999()
        {
            this.Header_999 = new HashSet<Header_999>();
        }
     [Key]
        public int GroupKey { get; set; }
        public Nullable<int> Interkey { get; set; }
        public string GS01_FunctionalIdCode { get; set; }
        public string GS02_ApplicationSendersCode { get; set; }
        public string GS03_ApplicationReceiversCode { get; set; }
        public string GS04_Date { get; set; }
        public string GS05_Time { get; set; }
        public string GS06_GroupControlNumber { get; set; }
        public string GS07_ResponsibleAgencyCode { get; set; }
        public string GS08_VersionReleaseIDCode { get; set; }
        public string GE01_NumberOfTransactionSets { get; set; }
        public string GE02_GroupControlNumber { get; set; }
    
        public virtual Interchange_999 Interchange_999 { get; set; }
        public virtual ICollection<Header_999> Header_999 { get; set; }
    }
}
