//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI_Entites._999Entites
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ImplementationDataSegment_999
    {
        public ImplementationDataSegment_999()
        {
           
            this.ImplementationDataElement_999 = new HashSet<ImplementationDataElement_999>();
            this.Context_999 = new HashSet<Context_999>();
        }
        [Key]
        public int ImplementationDataSegmentkey { get; set; }
        public Nullable<int> TransactionSetResponsekey { get; set; }
        public Nullable<int> Headerkey { get; set; }
        public string IK301_SegmentIDCode { get; set; }
        public string IK302_SegmentPositionInTransactionSet { get; set; }
        public string IK303_LoopIdentifierCode { get; set; }
        public string IK304_ImplementationSegmentSyntaxError { get; set; }
    
      
        public virtual Header_999 Header_999 { get; set; }
        public virtual ICollection<ImplementationDataElement_999> ImplementationDataElement_999 { get; set; }
        public virtual TransactionSetResponse_999 TransactionSetResponse_999 { get; set; }
        public virtual ICollection<Context_999> Context_999 { get; set; }
    }
}
