//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI_Entites._999Entites
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class ImplementationDataElement_999
    {
        public ImplementationDataElement_999()
        {
            this.Context_999 = new HashSet<Context_999>();
        }
     [Key]
        public int ImplementationDataElementkey { get; set; }
        public Nullable<int> ImplementationDataSegmentkey { get; set; }
        public Nullable<int> Headerkey { get; set; }
        public string IK4_SegmentHeader { get; set; }
        public string IK401_PositioninSegment { get; set; }
        public string IK401_01_ElementPositionInSegment { get; set; }
        public string IK401_02_ComponentDataElementPositionInComposite { get; set; }
        public string IK401_03_RepeatingDataElementPosition { get; set; }
        public string IK402_DataElementReferenceNumber { get; set; }
        public string IK403_DataElementErrorCode { get; set; }
        public string IK404_CopyOfBadDataelement { get; set; }
    
        public virtual ICollection<Context_999> Context_999 { get; set; }
        public virtual Header_999 Header_999 { get; set; }
        public virtual ImplementationDataSegment_999 ImplementationDataSegment_999 { get; set; }
    }
}
