//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIEntites
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2000C_BillingPayToProviderOfServiceLevel_277_214
    {
        
    
        public int BillingPayToProviderOfServiceLevelKey { get; set; }
        public Nullable<int> Headerkey { get; set; }
        public string HL01_ProviderHierarchicalIDNumber { get; set; }
        public string HL02_ProviderHierarchicalParentIDNumber { get; set; }
        public string HL03_ProviderHierarchicalLevelCode { get; set; }
        public string HL04_ProviderHierarchicalChildCode { get; set; }
        public string NM101_ProviderEntityIDCode { get; set; }
        public string NM102_ProviderEntityTypeQualifier { get; set; }
        public string NM103_ProviderOrganizationName { get; set; }
        public string NM104_ProviderFirstName { get; set; }
        public string NM105_ProviderMiddleName { get; set; }
        public string NM107_ProviderSuffixName { get; set; }
        public string NM108_ProviderIdentificationCodeQualifier { get; set; }
        public string NM109_ProviderIdentificationCode { get; set; }
        public string TRN01_ProviderTraceTypeCode { get; set; }
        public string TRN02_ProviderReferenceIdentification { get; set; }
        public string REF01_ProviderReferenceIdQualifier_01 { get; set; }
        public string REF02_ProviderReferenceId_01 { get; set; }
        public string REF01_ProviderReferenceIdQualifier_02 { get; set; }
        public string REF02_ProviderReferenceId_02 { get; set; }
        public string REF01_ProviderReferenceIdQualifier_03 { get; set; }
        public string REF02_ProviderReferenceId_03 { get; set; }
        public string QTY01_ProviderApprovedQuantityQualifier { get; set; }
        public string QTY02_ProviderApprovedQuantity { get; set; }
        public string QTY01_ProviderDisapprovedQuantityQualifier { get; set; }
        public string QTY02_ProviderDisapprovedQuantity { get; set; }
        public string AMT01_ProviderInProcessAmountQualifier { get; set; }
        public string AMT02_ProviderInProcessMonetaryAmount { get; set; }
        public string AMT01_ProviderReceivedAmountQualifier { get; set; }
        public string AMT02_ProviderReceivedMonetaryAmount { get; set; }
    
    }
}
