//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIEntites
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2000A_InformationSourceLevel_277_214
    {
        

        public int InformationSourceLevelKey { get; set; }
        public Nullable<int> Headerkey { get; set; }
        public string HL01_HierarchicalIDNumber { get; set; }
        public string HL03_HierarchicalLevelCode { get; set; }
        public string HL04_HierarchicalChildCode { get; set; }
        public string NM101_EntityIDCode { get; set; }
        public string NM102_EntityTypeQualifier { get; set; }
        public string NM103_OrganizationName { get; set; }
        public string NM108_PayerIdentificationCodeQualifier { get; set; }
        public string NM109_PayerIdentificationCode { get; set; }
        public string TRN01_SourceTraceTypeCode { get; set; }
        public string TRN02_SourceReferenceIdentification { get; set; }
        public string DTP01_ReceivedClaimDateTimeQualifier { get; set; }
        public string DTP02_ReceivedClaimDateTimePeriodFormatQualifier { get; set; }
        public string DTP03_ReceivedClaimDateTimePeriod { get; set; }
        public string DTP01_ProcessClaimDateTimeQualifier { get; set; }
        public string DTP02_ProcessClaimDateTimePeriodFormatQualifier { get; set; }
        public string DTP03_ProcessClaimDateTimePeriod { get; set; }
        public string HL01_ReceiverHierarchicalIDNumber { get; set; }
        public string HL02_ReceiverHierarchicalParentIDNumber { get; set; }
        public string HL03_ReceiverHierarchicalLevelCode { get; set; }
        public string HL04_ReceiverHierarchicalChildCode { get; set; }
        public string NM101_ReceiverEntityIDCode { get; set; }
        public string NM102_ReceiverEntityTypeQualifier { get; set; }
        public string NM103_RecieverOrganizationName { get; set; }
        public string NM104_ReceiverFirstName { get; set; }
        public string NM105_ReceiverMiddleName { get; set; }
        public string NM108_ReceiverIdentificationCodeQualifier { get; set; }
        public string NM109_ReceiverIdentificationCode { get; set; }
        public string TRN01_ReceiverTraceTypeCode { get; set; }
        public string TRN02_ReceiverReferenceIdentification { get; set; }
        public string QTY01_ReceiverAcknowledgedQuantityQualifier { get; set; }
        public string QTY02_ReceiverAcknowledgedQuantity { get; set; }
        public string QTY01_ReceiverUnacknowledgedQuantityQualifier { get; set; }
        public string QTY02_ReceiverUnacknowledgedQuantity { get; set; }
        public string AMT01_ReceiverInProcessAmountQualifier { get; set; }
        public string AMT02_ReceiverInProcessMonetaryAmount { get; set; }
        public string AMT01_ReceiverReceivedAmountQualifier { get; set; }
        public string AMT02_ReceiverReceivedMonetaryAmount { get; set; }
    
    }
}
