//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIEntites
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2000D_PatientLevel_277_214
    {
      
    
        public int PatientLevelKey { get; set; }
        public Nullable<int> BillingPayToProviderOfServiceLevelKey { get; set; }
        public string HL01_PatientHierarchicalIDNumber { get; set; }
        public string HL02_PatientHierarchicalParentIDNumber { get; set; }
        public string HL03_PatientHierarchicalLevelCode { get; set; }
        public string NM101_PatientEntityIDCode { get; set; }
        public string NM102_PatientEntityTypeQualifier { get; set; }
        public string NM103_PatientOrganizationName { get; set; }
        public string NM104_PatientFirstName { get; set; }
        public string NM105_PatientMiddleName { get; set; }
        public string NM107_PatientNameSuffix { get; set; }
        public string NM108_PatientIdentificationCodeQualifier { get; set; }
        public string NM109_PatientIdentificationCode { get; set; }
    
       
    }
}
