//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIEntites
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2200D_PatientAccountNumber_277_214
    {
       
    
        public int PatientAccountNumberKey { get; set; }
        public Nullable<int> PatientLevelKey { get; set; }
        public string TRN01_PatientTraceTypeCode { get; set; }
        public string TRN02_PatientReferenceIdentificationTraceNumber { get; set; }
        public string REF01_PatientPayorClaimIdQlfr { get; set; }
        public string REF02_PatientPayorClaimReferenceId { get; set; }
        public string REF01_PatientClaimIdQlfr { get; set; }
        public string REF02_PatientClaimReferenceId { get; set; }
        public string REF01_PatientBillingTypeIdQlfr { get; set; }
        public string REF02_PatientBillingTypeReferenceId { get; set; }
        public string DTP01_PatientServiceClaimDateTimeQualifier { get; set; }
        public string DTP02_PatientServiceClaimDateTimePeriodFormatQualifier { get; set; }
        public string DTP03_PatientServiceClaimDateTimePeriod { get; set; }
    
       
    }
}
