//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIEntites
{
    using System;
    using System.Collections.Generic;

    public partial class C2200B_STC_StatusInformation_277_214
    {
        public int BSTCKey { get; set; }
        public Nullable<int> InformationSourceLevelKey { get; set; }
        public string STC01_1_ReceiverCategoryCode { get; set; }
        public string STC01_2_ReceiverStatusCode { get; set; }
        public string STC01_3_ReceiverEntityIdentifierCode { get; set; }
        public string STC02_ReceiverDate { get; set; }
        public string STC03_ReceiverActionCode { get; set; }
        public string STC04_ReceiverMonetaryAmount { get; set; }
        public string STC10_1_ReceiverIndustryCode { get; set; }
        public string STC10_2_ReceiverIndustryCode { get; set; }
        public string STC10_3_ReceiverEntityIdentifierCode { get; set; }
        public string STC11_1_ReceiverIndustryCode { get; set; }
        public string STC11_2_ReceiverIndustryCode { get; set; }
        public string STC11_3_ReceiverEntityIdentifierCode { get; set; }
    }
       
}
