//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIEntites
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2200C_STC_StatusInformation_277_214
    {
        public int CSTCKey { get; set; }
        public Nullable<int> BillingPayToProviderOfServiceLevelKey { get; set; }
        public string STC01_1_ProviderCategoryCode { get; set; }
        public string STC01_2_ProviderStatusCode { get; set; }
        public string STC01_3_ProviderEntityIdentifierCode { get; set; }
        public string STC03_ProviderActionCode { get; set; }
        public string STC04_ProviderMonetaryAmount { get; set; }
        public string STC10_1_ProviderIndustryCode { get; set; }
        public string STC10_2_ProviderIndustryCode { get; set; }
        public string STC10_3_ProviderEntityIdentifierCode { get; set; }
        public string STC11_1_ProviderIndustryCode { get; set; }
        public string STC11_2_ProviderIndustryCode { get; set; }
        public string STC11_3_ProviderEntityIdentifierCode { get; set; }
    
       
    }
}
