//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIEntites
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2220D_STC_StatusInformation_277_214
    {
        public int DDSTCKey { get; set; }
        public Nullable<int> PatientServiceLineInformationKey { get; set; }
        public string STC01_1_PatientCategoryCode { get; set; }
        public string STC01_2_PatientStatusCode { get; set; }
        public string STC01_3_PatientEntityIdentifierCode { get; set; }
        public string STC03_PatientActionCode { get; set; }
        public string STC10_1_PatientIndustryCode { get; set; }
        public string STC10_2_PatientIndustryCode { get; set; }
        public string STC10_3_PatientEntityIdentifierCode { get; set; }
        public string STC11_1_PatientIndustryCode { get; set; }
        public string STC11_2_PatientIndustryCode { get; set; }
        public string STC11_3_PatientEntityIdentifierCode { get; set; }
        public string STC12_PatientFreeFormMessage { get; set; }
    
      
    }
}
