//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIEntites
{
    using System;
    using System.Collections.Generic;
    
    public partial class C2220D_ServiceLineInformation_277_214
    {
      
    
        public int PatientServiceLineInformationKey { get; set; }
        public Nullable<int> PatientAccountNumberKey { get; set; }
        public string SVC01_1_PatientProductServiceIDQualifier { get; set; }
        public string SVC01_2_PatientProductServiceID { get; set; }
        public string SVC01_3_PatientProcedureModifier { get; set; }
        public string SVC01_4_PatientProcedureModifier { get; set; }
        public string SVC01_5_PatientProcedureModifier { get; set; }
        public string SVC01_6_PatientProcedureModifier { get; set; }
        public string SVC02_PatientServiceLineMonetaryAmount { get; set; }
        public string SVC04_PatientServiceLineProductServiceID { get; set; }
        public string SVC07_PatientServiceLineQuantity { get; set; }
        public string REF01_PatientLineItemControlIdQlfr { get; set; }
        public string REF02_PatientLineItemControlReferenceId { get; set; }
        public string REF01_PatientPharmacyIdQlfr { get; set; }
        public string REF02_PatientPharmacyReferenceId { get; set; }
        public string DTP01_PatientServiceLineDateTimeQualifier { get; set; }
        public string DTP02_PatientDateTimePeriodFormatQualifier { get; set; }
        public string DTP03_PatientServiceLineDateTimePeriod { get; set; }
    
      
    }
}
