//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIEntites
{
    using System;
    using System.Collections.Generic;
    
    public partial class FunctionalGroup_277_214
    {
        public FunctionalGroup_277_214()
        {
            this.Header_277_214 = new HashSet<Header_277_214>();
        }
    
        public int Groupkey { get; set; }
        public Nullable<int> Interkey { get; set; }
        public string GS01_FunctionalIdCode { get; set; }
        public string GS02_ApplicationSendersCode { get; set; }
        public string GS03_ApplicationReceiversCode { get; set; }
        public string GS04_Date { get; set; }
        public string GS05_Time { get; set; }
        public string GS06_GroupControlNumber { get; set; }
        public string GS07_ResponsibleAgencyCode { get; set; }
        public string GS08_VersionReleaseIDCode { get; set; }
        public string GE01_NumberOfTransactionSets { get; set; }
        public string GE02_GroupControlNumber { get; set; }
    
        public virtual Interchange_277_214 Interchange_277_214 { get; set; }
        public virtual ICollection<Header_277_214> Header_277_214 { get; set; }
    }
}
