//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDIEntites
{
    using System;
    using System.Collections.Generic;
    
    public partial class Header_277_214
    {
        public Header_277_214()
        {
            this.C2000A_InformationSourceLevel_277_214 = new HashSet<C2000A_InformationSourceLevel_277_214>();
            this.C2000C_BillingPayToProviderOfServiceLevel_277_214 = new HashSet<C2000C_BillingPayToProviderOfServiceLevel_277_214>();
        }
    
        public int Headerkey { get; set; }
        public Nullable<int> Groupkey { get; set; }
        public string ST01_TransactionSetIdentifierCode { get; set; }
        public string ST02_TransactionSetControlNumber { get; set; }
        public string ST03_ImplementationConventionReference { get; set; }
        public string BHT01_HierarchicalStructureCode { get; set; }
        public string BHT02_TransactionSetPurposeCode { get; set; }
        public string BHT03_ReferenceIdentification { get; set; }
        public string BHT04_TransactionSetCreationDate { get; set; }
        public string BHT05_Time { get; set; }
        public string BHT06_TransactionTypeCode { get; set; }
        public string SE01_TransactionSegmentCount { get; set; }
        public string SE02_TransactionSetControlNumber { get; set; }
    
        public virtual ICollection<C2000A_InformationSourceLevel_277_214> C2000A_InformationSourceLevel_277_214 { get; set; }
        public virtual ICollection<C2000C_BillingPayToProviderOfServiceLevel_277_214> C2000C_BillingPayToProviderOfServiceLevel_277_214 { get; set; }
        public virtual FunctionalGroup_277_214 FunctionalGroup_277_214 { get; set; }
    }
}
